debian: Depend on libgbinder (>= 1.1.20)
Older libgbinder is no longer supported due to e.g. the following seen
under Ubuntu Touch 16.04 from "import gbinder":

  ImportError: /usr/lib/python3/dist-packages/gbinder.cpython-35m-aarch64-linux-gnu.so: undefined symbol: gbinder_servicemanager_new2